### ISSUE TITLE
Help for freedom

### ISSUE THREAD

**Issue by javadsmh** [vpnhood/VpnHood#223]
your servers are blocked by Islamic republic of iran please do some things

**Comment by bobvhood** [comment]
Hi,
Thank you for sharing this with us.

The public servers were for test purposes only; thousands of users are now connecting to private VpnHood servers. We don't have any plan to change our public server IPs because they will be blocked sooner or later. We are developing the software and trying to improve the protocol and its performance. So if you need a reliable and fast VPN, you need to find a private server from a third party. I am sorry for this inconvenience.
