### ISSUE TITLE
New Feature

### ISSUE THREAD

**Issue by Amirsomeh** [vpnhood/VpnHood#239]
hi dear friend
I had some suggestion
* could use domain and DNS on this VPN to avoid IP blocking
* Use speed and bandwidth limits for users
* Using more protocols and settings to make access key in the panel

**Comment by trudyhood** [comment]
Hi, Thank you for your recommendataions

> could use domain and DNS on this VPN to avoid IP blocking

 We have the plan to use domains instead of IP but for other purposes. it does not help with IP blocking, as domain blocking is much more common and permanent than  IP blocking unless users use DNSSEC, which is not so common at this time.

> Use speed and bandwidth limits for users

It is not our priority at the moment.

>Using more protocols and settings to make access key in the panel

Yes, we are working hard to improve more features like these.
