### ISSUE TITLE
Can not connect!

### ISSUE THREAD

**Issue by roozbehsat** [vpnhood/VpnHood#241]
Hi trudy.
After you solved the problem about deleted token, my client can not connect to server.
Please help me.

**Comment by trudyhood** [comment]
hi. what's the problem? can you connect to your server yourself?

**Comment by roozbehsat** [comment]
Yes, I can connect to my server with ssh protocol.

**Comment by trudyhood** [comment]
i meant by vpnhood

**Comment by roozbehsat** [comment]
with vpnhood I Can't

**Comment by trudyhood** [comment]
please send me an access token
***@***.***

**Comment by roozbehsat** [comment]
vh://eyJuYW1lIjoiUm9vemJlaCIsInYiOjEsInNpZCI6MTAxOCwidGlkIjoiMTQ2ZDM1YWMtYzY4OC00ZDcwLWIyZGUtNTk3YTY4NDkzNzkwIiwic2VjIjoibXRDVm8xK1IwYXRlRFVCT3hWVmI0QT09IiwiaXN2IjpmYWxzZSwiaG5hbWUiOiJudS5oZWx5YnVteS5uZXQiLCJocG9ydCI6MCwiY2giOiJlKzk0VXFiOWNIMW85Zzk3ckdDRW1jTkhaWDg9IiwicGIiOmZhbHNlLCJ1cmwiOm51bGwsImVwIjpbIjEyOC4xOTkuMzUuMzA6NDQzIl19

**Comment by trudyhood** [comment]
i can connect to your sever and it is working

**Comment by trudyhood** [comment]
perhaps the token hasn't been updated. please make sure they use the new token. check that with the supportid. i have to leave the office. see you next day.

**Comment by roozbehsat** [comment]
May I ask u a question?
Can the network provider filter the vpnhood? Because I check two more server in one internet provider, but it wont work, but in another provider, it worked successfully.

**Comment by trudyhood** [comment]
They can easily block your IP or domain, but they can't detect the VpnHood protocol; also, we are trying to improve its protocol every day. So you should not create a public server and distribute its tokens to anyone. You must create a server for a few people (perhaps 100-500), then switch to another server. If your internet provider finds your server IP, you should never give those people a new token from another server because one of them will report that server IP again.

VpnHood works best for families, personal, groups of friends, or paid plans but is not good if you want to create some servers and distribute tokens unmanaged everywhere.

https://github.com/vpnhood/VpnHood/wiki/Can-a-network-provider-block-VpnHood
