### ISSUE TITLE
User's data usage update

### ISSUE THREAD

**Issue by free-keyboards** [vpnhood/VpnHood#261]
I've checked the users' account usage log (/opt/VpnHoodServer/storage/access/<uuid>.usage), it only gets updated when user press disconnect button on client applications and if user closes the application before pressing disconnect button, it wouldn't update user usage and doesn't close their session and these non-terminated sessions will be closed after about 20 minutes avg. (tested in android app)
(checking the sessions log /opt/VpnHoodServer/storage/logs/sessions.log)

**Comment by trudyhood** [comment]
Hi, Thank you for providing these detail. That's right; it is the behavior of VpnHood design. However, it should update the usage after 20 minutes unless something unexpected happens. In its worse use can use 100MB more than expected because the server syncs the data before 100 MB, which is configurable. VpnHood server also syncs user data every 20 minutes.

You will also have much more control over users if you use VpnHood Access Server:
https://github.com/vpnhood/VpnHood/wiki/VpnHood-Access-Server

I still need help understanding the issue you reported. Did you mean it doesn't save user data after 20 minutes? I double-checked the File Access Server code and couldn't see any issue. If you still see the problem let me know the version of your server so we can go more deeply into it.
