### ISSUE TITLE
 The remote certificate was rejected by the provided RemoteCertificateValidationCallback

### ISSUE THREAD

**Issue by parsagholipour** [vpnhood/VpnHood#279]
I used docker on linux and I get this error trying to connect
[log.txt](https://github.com/vpnhood/VpnHood/files/10774429/log.txt)

**Comment by trudyhood** [comment]
I think your docker doesn't map 443 port to your doctor. perhaps you are trying to another service. Do you use VpnHood access server or built in file server?
if you are using the file access server make sure that you have configured it's a storage location properly otherwise every time you run the container a new certificate will regenerated

**Comment by parsagholipour** [comment]
443 port is already used by another service(nginx) . So I can't have them working together?

**Comment by trudyhood** [comment]
Only one service can listen to a port. So You need to use another port for VpnHood, such as 4443
For more information, read this:
https://github.com/vpnhood/VpnHood/wiki/Address-Already-In-Use
