### ISSUE TITLE
googe does not work 

### ISSUE THREAD

**Issue by asoMansoury** [vpnhood/VpnHood#321]
A lot of clients reported that while they are using the VpnHood  cannot use google.com and they got 403 error from google.
![image](https://user-images.githubusercontent.com/14541559/236516432-b155ebf1-aeaa-45a3-93e9-d8ca04fdcbba.png)

**Comment by trudyhood** [comment]
Yes, we have encountered this issue, and it does not belong to any VPN technology:
https://github.com/vpnhood/VpnHood/wiki/How-Google-detects-my-location-when-I-use-a-VPN

**Comment by asoMansoury** [comment]
> Yes, we have encountered this issue, and it does not belong to any VPN technology: https://github.com/vpnhood/VpnHood/wiki/How-Google-detects-my-location-when-I-use-a-VPN

Can you provide an ability to define some websites on VPNHood Client to not use the Vpn's IP,  for example www.google.com in this scenario.
by providing this feature the problem will be solved.

**Comment by trudyhood** [comment]
Do you mean that google let them use that service with users actual ip but not vpn ip?

**Comment by asoMansoury** [comment]
> Do you mean that google let them use that service with users actual ip but not vpn ip?

Exactly.
it is really a great feature like of app's that you have provided on  mobile app.

**Comment by trudyhood** [comment]
You need to use ip filtering. Exclude Google IPs from your server. unfortunately we don't provide ui to do that on client app.

**Comment by asoMansoury** [comment]
> You need to use ip filtering. Exclude Google IPs from your server. unfortunately we don't provide ui to do that on client app.

It's ok on server. but I just want to www.google.com not other google's services.
how do I can implement this feature for clients?

**Comment by trudyhood** [comment]
VpnHood doesn't support domain filtering, which means you would need to obtain the IP addresses of the websites you want to access through it. However, it's not certain if this method would work. Regarding the error message you shared, it's unlikely that it belongs to [www.google.com](http://www.google.com/) because Google's search engine usually works worldwide. It's possible that the error message pertains to another Google service that is restricted in your region.
