### ISSUE TITLE
Abuse notification

### ISSUE THREAD

**Issue by asoMansoury** [vpnhood/VpnHood#322]
Hello
I got this error from trafiq.com
Do you have any suggestion for solving this issue?
.........

Dear XXX ,

We have received an abuse report from [ncsc-fi-autoreporter@traficom.fi](mailto:ncsc-fi-autoreporter@traficom.fi).

We are automatically forwarding this complaint on to you, for your information. You do not need to respond, but we do expect you to check the report and to resolve any (potential) issues.

Information:

-----

NCSC-FI has received information regarding IP-addresses in your network which may have security problems. The information regarding the problems is included as an attachment in CSV format. Data lines have the following format:
asn|ip|source time|domain name|cc|type|uuid|info

Here cc refers to the country code, type to the type of the security problem, and uuid is the unique identifier of the event in Autoreporter. The info column is reserved for any additional information. The column always includes an anonymous identifier for the datasource that is used in the report. All timestamps are given in UTC.

This report is electronically signed using the PGP-key of Autoreporter. The key is available at
https://www.kyberturvallisuuskeskus.fi/sites/default/files/media/file/NCSC-FI_AUTOREPORTER_2019-2024.txt

**Comment by trudyhood** [comment]
Some users may fall victim to malware on their machines that perform unauthorized actions, such as Netscan and local port scans, without their knowledge. Some hosting providers, like Hetzner, may mistakenly attribute this activity to the server software and blame the hosting company. However, other providers may not be concerned about it. When users connect to your VPN server, any such activity will originate from your server because they share your server network.

One solution is to consider changing your hosting provider. Alternatively, VpnHood offers a NetScan Protector feature that can help mitigate these issues. However, using this feature may impact the quality of your service and interfere with normal usage. Before deciding on any action, you should first investigate what kind of abuse has been reported by your hosting provider. Based on that information, I may be able to recommend some configuration changes that could help.

**Comment by asoMansoury** [comment]
> 

Ok.
Do you have any article for having best configuration on servers.

**Comment by trudyhood** [comment]
We have not found a solution yet. We have experimented with some configurations for Hetzner, but some users may experience connectivity issues. I can share the configuration details with you, but please be aware that it may not provide a reliable solution.

**Comment by asoMansoury** [comment]
> We don't have the document yet. We have experimented with some configurations for Hetzner, but some users may experience connectivity issues. I can share the configuration details with you, but please be aware that it may not provide a reliable solution.

it is OK.
I will check the configuration.
can you send it to my email?
aso.mansoury@gmail.com

**Comment by trudyhood** [comment]
give me time and i will post it here.
