### ISSUE TITLE
Linux Client

### ISSUE THREAD

**Issue by AndrewDuffyJr** [vpnhood/VpnHood#332]
Title says it all, a client to use the VPN on Linux.

**Comment by mrbluecoat** [comment]
Just curious, any particular reason this is not planned?

**Comment by trudyhood** [comment]
> Just curious, any particular reason this is not planned?

The reason this isn't planned is primarily due to a combination of factors. First, there is currently very little demand for Linux clients. Our resources are limited, and we prioritize tasks and features based on user demand and potential impact.

However, we highly value user feedback and suggestions. If there is a strong demand for this feature in the future or if circumstances change, we'll definitely reconsider our priorities. Your input is important to us, and we appreciate your curiosity and interest in our products/services.

**Comment by mrbluecoat** [comment]
Makes total sense. Awesome VPN, by the way!

**Comment by mfat** [comment]
Another vote for a linux client. Thanks!

**Comment by sabershahhoseini** [comment]
Another vote for a linux client. Would be great!

**Comment by trudyhood** [comment]
We already have this repo, waiting for someone to participate by writing and testing its PacketFilter:
https://github.com/vpnhood/VpnHood.Client.Linux
