### ISSUE TITLE
Manually close a specific session

### ISSUE THREAD

**Issue by AmirHosseinCV** [vpnhood/VpnHood#338]
Is there a way to manually close a session by its ID?
![image](https://github.com/vpnhood/VpnHood/assets/46716338/d4bbf42f-5f1e-4abe-9b22-246cdcbade1d)

**Comment by bobvhood** [comment]
Let me know if I understand correctly. It seems like you have shared a single token and now need to block a connection. Logically, it is not possible to detect a user without a login. However, there is a ClientID available, but it can also be reset from the user's side. While there may be some tricks to obtain a persistent device ID, they involve dirty work and also violate user privacy. I also noticed that you are using a file access server.

Solution 1:
You can assign a separate token to each user and delete it when you want to block their access.

Solution 2:
You can utilize the VpnHood Enterprise Access server and create a public token. Then, you can block a user based on their IP or device ID. We can add a DeviceID block to our interface, but keep in mind that the device ID can be reset by the user, allowing them to regain access. Even if we capture a persistent device ID from the client, it would not be reliable as there are many VpnHood clients available and we cannot enforce specific code in their app since VpnHood is open-source and its protocol is open. Please check our access server at: https://console.vpnhood.com/
![image](https://github.com/vpnhood/VpnHood/assets/92276967/cb88359e-4ae1-431c-97fe-3f7a41c0842f)


Solution 3:
You can consider developing your own access server, but I'm doubtful that you'll be able to achieve your goal due to the problem I described.
