### ISSUE TITLE
Could not find any public IP to add to the token. Check -ep option.

### ISSUE THREAD

**Issue by rifaldi34** [vpnhood/VpnHood#413]
[20:11:03.5083] fail: [0]
      Could not find any public IP to add to the token. Check -ep option.
      
     
![image](https://github.com/vpnhood/VpnHood/assets/29375886/34d035e2-b7c0-4c91-9b4d-5fe08c4b0b86)

**Comment by trudyhood** [comment]
Hi,
How do you generate access keys?

**Comment by NoRRt** [comment]
Hello, I have the same problem
 
 Could not find any public IP to add to the token. Check -ep option.

This is how I got the key : (docker run -v "/opt/VpnHoodServer/storage:/app/storage" "vpnhood/vpnhoodserver" gen)

There must be a way - to set the IP of the server on VpnHood Server (of course manually) because some servers have multiple IPs.

**Comment by trudyhood** [comment]
Make sure you have the recent version. 
However you can use gen -? and see the options. then set the ep
gen -ep IP1,IP2
