### ISSUE TITLE
Memory. Windows app

### ISSUE THREAD

**Issue by Onair-santa** [vpnhood/VpnHood#416]
![explorer_SyH3uQF4oc](https://github.com/vpnhood/VpnHood/assets/42511409/0c5be75e-8404-4786-a95a-fddae24f84bd)
Is it normal?

**Comment by Onair-santa** [comment]
1.75 Gb

**Comment by trudyhood** [comment]
Is it the client! No it is not. We have to check it out.

**Comment by trudyhood** [comment]
how much memory your system have? maybe you have a lot so garbage collector let it grow till system request clean up. anyway, I put it in our priority tasks to make sure there is no memory leak.

**Comment by Onair-santa** [comment]
16 Gb
1h work and 1.7 Gb memory
3.0.416 win app

**Comment by Onair-santa** [comment]
And now is 200Mb 
May be system error

**Comment by trudyhood** [comment]
I don't think it was a system error. To improve performance and prevent memory fragmentation .NET Garbage Collector lets memory usage grow if you have a lot of memory free, but as soon as your system memory goes near stress or at some period of time it releases the extra memory.

Let us know if you find the memory usage is too high especially when there is not enough memory left on your system.

**Comment by Onair-santa** [comment]
Well, immediately there’s something similar on the server, 100% CPU load for 24 hours already
![chrome_2nWbLYITgZ](https://github.com/vpnhood/VpnHood/assets/42511409/d87b569a-ec83-4ada-8adf-d0698af5fb67)

**Comment by Onair-santa** [comment]
![chrome_3EWWqmphyj](https://github.com/vpnhood/VpnHood/assets/42511409/428aa76d-e807-4070-87c0-f3c7cf4f2909)

**Comment by Onair-santa** [comment]
automatic update is evil
This is the second time I’m writing to you and dozens of computers have already died because of this.
Remove automatic updates from computer programs and servers

**Comment by trudyhood** [comment]
We are very sorry for any inconvenience that may be caused by the auto-updates, and we understand your concern about potential failures resulting from these updates. If you wish to disable automatic updates, you can do so by stopping the VpnHoodUpdater service with the following command:

Run the following command after installing or updating VpnHood servers
```sh
sudo systemctl stop VpnHoodUpdater
```

⚠️ It is essential to consider the implications of disabling automatic updates, as this may lead to various issues due to insufficient resources for maintaining long-term backward compatibility. We believe that it will result in increased service downtime for your clients.

Here are some key points to consider:

* Regular upgrades of VpnHood clients may result in the discontinuation of support for older servers, requiring manual updates for all servers to ensure continued client-server connectivity.
* Recent failures were not solely caused by the latest updates but also resulted from the termination of certain free IP reporting services. Consequently, failure to update servers manually may lead to service disruptions upon restarting.
* Disabling updates can lead to challenges in performing large-scale updates in the future, necessitating the manual update of all previous versions sequentially to maintain server data integrity.
* Some updates are critical for ensuring robust server security and safeguarding against evolving cyber threats.
* Discontinuation of support for older servers by the VpnHood Access Manager may lead to significant failures if your services heavily rely on this feature.

We'd like to encourage you to carefully assess the risks associated with disabling automatic updates and consider implementing a comprehensive strategy that balances the need for stability and security with the potential challenges of manual updates.
