### ISSUE TITLE
Connection issue

### ISSUE THREAD

**Issue by 4Waifu** [vpnhood/VpnHood#478]
Since this morning(it's around 10-12am around here ATM), i cannot longer access most of the sites with a few exceptions(i can access [REDACTED] and maybe some more) with VpnHood being turned on.
Is this a last goodbye for yet another old friend of mine that I've been with for so long, or is there still a chance?

https://youtu.be/1okn3YNk-ro

**Comment by trudyhood** [comment]
Hi,
thank you for trying VpnHood.

1) What is 2ch/4ch? 
2) Are you using VpnHood public servverd?
3) Which country are you from?

Also, your video us not accessible from the US.

**Comment by 4Waifu** [comment]
> Hi, thank you for trying VpnHood.
> 
> 1. What is 2ch/4ch?
> 2. Are you using VpnHood public servverd?
> 3. Which country are you from?
> 
> Also, your video us not accessible from the US.

5632e925@20240308T082235-23896384 I've sent "Bug Report"

**Comment by trudyhood** [comment]
OK, it is so weird that you can access some sites and some not. It should be nothing or all. Would you tell me which site does not work? 
Also, I am wondering how public servers work in Russia, as I thought the IP should be already blocked because they are public; you might consider finding a hidden server.

**Comment by 4Waifu** [comment]
(I hope i am not providing help to further block VpnHood in Russia 😭)
I randomly popped some of mine bookmarks:
When turned VpnHood turned on:
twitch.tv ❌
twitter.com ❌
mail.google.com ❌
steamcommunity.com ❌
translate.google.com ❌

steamdb.info ✅
youtube.com ✅
vk.com ✅
mail.ru ✅
4chan.org ✅
2ch.hk ✅
translate.yandex.ru✅
deepl.com ✅
Google Search ✅

> you might consider finding a hidden server.

Are they paywalled, i would assume or..?

**Comment by trudyhood** [comment]
I verified that it was functioning correctly. Strangely, some websites work while others do not. Everything should either work or not.
1) Try disabling "Exclude My Country" and check the result. Also, 
2) make sure no proxy or browser plugin interferes with your connection.
3) Try using another device to make sure the problem is not rooted in your machine

**Comment by trudyhood** [comment]
Could you fix the issue?
