### ISSUE TITLE
About "access server " and its "Server farm"  

### ISSUE THREAD

**Issue by SalimiHabib** [vpnhood/VpnHood#484]
Hi 
in  "**VpnHood Access Manager**" web site  ,  there is a concept as " **server farm**" (below image ) ,  but cannot  find any document about it , also no comment in source code of Vpnhood , it seems as none public implementation of access server , we want to know its functionality  and also ,  we want to implement my own access server .
In `VPNHOOD `There is 2 type of  access manager and only one of them  will be use in each server instance , but it is not clear how can we have  an access server , how we be able to separate  `IAccessManager `implementation from `VpnHood.Server` , because  it is using access manager to handle **access keys** `CRUD`   for users  in both `CLI `and `API `form .
so in brief we need to know   
1.  what is server farm and its functionality 
2. how can i have my access server 

thank you 

![image](https://github.com/vpnhood/VpnHood/assets/23046553/0c8d0587-3ad7-4d7b-a1a0-7fcec29cb2e0)

**Comment by trudyhood** [comment]
Server Farm is a group of servers that help load balancing. Most apps use only one server farm and do not need multiple farms. You may need two separate farms, one for slow servers to provide free services, and another for fast servers to provide premium services.

All the functionality can be implemented through IAccessManager. VpnHood Access Manager is not mandatory as VpnHoodServer has a simple built-in implementation of IAccessManager called FileAccessManager. You can see how FileAccessManager is implemented and build your own. Also, there is HttpAccessManager that calls some REST API, so you can write your own access manager by implementing your own REST API.

Sorry, there is no sample for HttpAccessManager.

**Comment by SalimiHabib** [comment]
in server farm **access key** is generated for all servers in separate ,  or they share a common **token secret** and token is valid to all of them , how load balancing can be implemented conceptually ?

**Comment by trudyhood** [comment]
Please note that FarmToken is distinct from AccessTokens. FarmToken is shared among all servers and clients within a particular farm. In contrast, Access Token is a user credential that includes FarmToken. FarmToken functions as an access point, consisting of domain, IP, and a shared secret. It is shared among all servers and clients on the farm.

You cannot achieve this with FileAccessManager because it is isolated for each server and works independently. You need an enterprise Access Manager to orchestrate all servers in a farm.

![image](https://github.com/vpnhood/VpnHood/assets/72891124/d0891ba0-6d6c-4748-892c-93a0d65223fb)
