### ISSUE TITLE
Dual Messenger(cloned app) Problem

### ISSUE THREAD

**Issue by masihnazari** [vpnhood/VpnHood#502]
hi
hood client does not detect dual messenger on Samsung phones and only the original version of the app can use vpnhood traffic.
other VPN client apps like Open VPN or v2ray work fine with both versions of Messengers.

**Comment by trudyhood** [comment]
@petervhood Can you please check it out?

**Comment by trudyhood** [comment]
Please select ALL apps instead of using Exclude/Include Apps feature. Are you sure OpenVPN and v2Ray work with the "Exclude and Include" feature? Dual messenger is a customized feature of some specific bands like Samsung, which is not included in the Android standard. 
![image](https://github.com/vpnhood/VpnHood/assets/72891124/8b4df906-e49d-4483-b718-52549033b9be)

Android VpnService handles that, and it is not in the development hands.  Also, we checked it with "All Apps", and it seems it works. 

You can add comments to this closed issue if the "All Apps" does not solve the issue.
