### ISSUE TITLE
Feature Request: Ability to Specify Custom Storage Directory

### ISSUE THREAD

**Issue by greenfnnn814** [vpnhood/VpnHood#615]
I am using the VpnHood application and encountered a permission issue when it tries to access the default storage directory at `C:\Windows\storage`. Since I do not have administrative rights to modify the permissions for this directory, it would be helpful if the application allowed users to specify a custom storage directory.

This feature would enhance usability, especially for users who may not have the necessary permissions to access certain system directories. Allowing a configurable storage path would enable users to run the application seamlessly without running into access issues.

**Comment by trudyhood** [comment]
Hi, I assume you are talking about VpnHood CLIENT, not the Server.
VpnHood Client requires admin privilege to run its network capture adapter, so even if we change the installation directory to the user directory, it will not run because of the adapter permission.

By the way, thank you for sharing your requirements here.
