### ISSUE TITLE
How does vpnhood restrict clients?

### ISSUE THREAD

**Issue by vikofun** [vpnhood/VpnHood#91]
How to limit the traffic used every month?
How to limit bandwidth?

**Comment by bobvhood** [comment]
We are working on these and will be available soon.

> How to limit the traffic used every month?
We have implemented it, but it is not fully functional yet. You can achieve that through the VpnHood access server.
https://github.com/vpnhood/VpnHood/wiki/VpnHood-Access-Server

> How to limit bandwidth?
It is highly needed, we hope to implement it soon.

**Comment by vikofun** [comment]
expect!
I have registered a vpnhood access server account and don't quite understand how to use it.
VpnHood access server is a private project. Isn't it open source?

**Comment by bobvhood** [comment]
>VpnHood access server is a private project. Isn't it open source?

Yes, VpnHood Access Server is not an open-source project. We will implement the bandwidth limit in VpnHood Internal Access Server, which is open-source. 

>I have registered a VpnHood access server account and don't quite understand how to use it.
We would be grateful if you let us know which part was confusing?

**Comment by trudyhood** [comment]
We have decided not to implement bandwidth limitations due to the heavy impact on the server. We can move users to more busy servers so they automatically get slowed by other users, or we can create some premium servers with fewer users, and it eliminates the use of bandwidth control. Feel free to add your idea to this closed issue.
